# Generated by Django 3.2.15 on 2022-10-27 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20221027_1045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['parent'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
    ]
