# Generated by Django 3.2.15 on 2022-10-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_department_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id'], 'verbose_name': 'department', 'verbose_name_plural': 'departments'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['full_name'], 'verbose_name': 'employee', 'verbose_name_plural': 'employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='is_chief',
            field=models.BooleanField(default=False, verbose_name='is chief'),
        ),
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='employee.department', verbose_name='parent'),
        ),
    ]
